http:
  middlewares:
    basicHeaders:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true

  routers:
    api:
      rule: "Host(`api-prod.lesbulleurstoulonnais.fr`)"
      service: "api-service"
      entrypoints:
        - http
      middlewares:
        - basicHeaders

  services:
    api-service:
      loadBalancer:
        servers:
          - url: "http://nestjs_api:3000/"