version: "3.8"
services:
  #PostgreSQL
  postgres-db:
    image: postgres:latest
    container_name: api-postgres-db-test
    env_file:
    - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # NestJS
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-nestjs-test
    env_file:
      - .env
    environment:
      DB_HOST: postgres-db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_PORT: 5432
      NODE_ENV: development
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules
    # Commande pour installer les dépendances au démarrage du conteneur
    command: >
      bash -c "npm install
      && npm rebuild bcrypt --build-from-source
      && npm run start:dev"

volumes:
  postgres-data-test: