version: '3.8'

services:
  api:
    container_name: nestjs_api
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile.prod
    restart: unless-stopped
    depends_on:
      - postgres-db
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env  # Montage du fichier .env local dans le conteneur
    networks:
      - app-network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api-prod.lesbulleurstoulonnais.fr`)"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      # Ajout de la configuration pour la redirection HTTP -> HTTPS
      - "traefik.http.routers.api-http.rule=Host(`api-prod.lesbulleurstoulonnais.fr`)"
      - "traefik.http.routers.api-http.entrypoints=http"
      - "traefik.http.routers.api-http.middlewares=redirectToHttps"

  postgres-db:
    container_name: postgres_db
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  traefik:
    container_name: traefik
    image: traefik:v2.10
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./deploy/docker/traefik/config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./deploy/docker/traefik/dynamic:/etc/traefik/dynamic:ro
      - traefik_certificates:/etc/traefik/acme
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # Dashboard configuration
      - "traefik.http.routers.dashboard.rule=Host(`traefik.lesbulleurstoulonnais.fr`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=https"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      # Ajout de la redirection HTTP -> HTTPS pour le dashboard
      - "traefik.http.routers.dashboard-http.rule=Host(`traefik.lesbulleurstoulonnais.fr`)"
      - "traefik.http.routers.dashboard-http.entrypoints=http"
      - "traefik.http.routers.dashboard-http.middlewares=redirectToHttps"
      # Définition du middleware de redirection
      - "traefik.http.middlewares.redirectToHttps.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirectToHttps.redirectscheme.permanent=true"

networks:
  app-network:
    driver: bridge
  web:
    driver: bridge

volumes:
  postgres_data:
  traefik_certificates: