#version: "3.8"
services:
  # Service pour la bdd PostgreSQL
  postgres-db:
    image: postgres:latest
    container_name: api-postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service pour l'API NestJs
  nestjs-api:
    image: ghcr.io/${GITHUB_REPOSITORY}-api:${TAG}
    container_name: nestjs-api
    env_file:
      - ./.env
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    depends_on:
      postgres-db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - nestjs-api
    restart: always

volumes:
  postgres-data-test: