POST https://testassbtapi.nataliesimon.fr/api/articles/create
Content-Type: multipart/form-data; boundary=WebKitFormBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3NDAyNDM5NTIsImV4cCI6MTc0MDI0NzU1Mn0.Q67m3BcCsxWA66FHW8wzwsmODj1c5FDtZMjKRa8c8jQ

--WebKitFormBoundary
Content-Disposition: form-data; name="fichier"; filename="test.jpg"
Content-Type: image/jpeg

< ./images/image1.png
--WebKitFormBoundary
Content-Disposition: form-data; name="titre"

Test avec user 2
--WebKitFormBoundary
Content-Disposition: form-data; name="contenu"

<h1>Verdict</p><h1>Encore un <test>
--WebKitFormBoundary
Content-Disposition: form-data; name="statut"

publie
--WebKitFormBoundary
Content-Disposition: form-data; name="categorie"

accueil
--WebKitFormBoundary--
