POST http://localhost:3000/api/articles/create
Content-Type: multipart/form-data; boundary=WebKitFormBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3NDA5MzQ2NjgsImV4cCI6MTc0MDkzODI2OH0.INDCIynndNeJQpblj_GDDZJLuk3yZ3kIKstGlawxvEM


--WebKitFormBoundary
Content-Disposition: form-data; name="fichier"; filename="test.jpg"
Content-Type: image/jpeg

< ./images/image1.png
--WebKitFormBoundary
Content-Disposition: form-data; name="titre"

Vente d'un ponney
--WebKitFormBoundary
Content-Disposition: form-data; name="contenu"

<h1>Verdict</p><h1>Déjà pratiqué le sport aquatique <test>
--WebKitFormBoundary
Content-Disposition: form-data; name="statut"

publie
--WebKitFormBoundary
Content-Disposition: form-data; name="categorie"

annonce
--WebKitFormBoundary--
