GET http://localhost:3000/api/categories-articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJyb2xlIjoiQWRtaW4iLCJwcm9maWwiOnsiaWQiOjEsIm5vbSI6InNpbW9uIiwicHJlbm9tIjoibmF0YWxpZSIsInRlbGVwaG9uZSI6IjEyMzQ1Njk4NzAiLCJjb21tdW5pY2F0aW9uX21haWwiOnRydWUsImNvbW11bmljYXRpb25fc21zIjpmYWxzZSwiYXZhdGFyIjp7ImlkIjoxLCJub20iOiJqb2NlLTE3NDMxMDAxMjY1MTYtNGE3OThkN2QtYjhiMy00NGNlLWI2ZDAtZjk2YmZkNzZiMjljLmpwZyIsInVybCI6Imh0dHBzOi8vYXBpdGVzdC5uYXRhbGllc2ltb24uZnIvdXBsb2Fkcy9qb2NlLTE3NDMxMDAxMjY1MTYtNGE3OThkN2QtYjhiMy00NGNlLWI2ZDAtZjk2YmZkNzZiMjljLmpwZyIsInR5cGUiOiJpbWFnZSIsIm1pbWUiOiJpbWFnZS9qcGVnIiwidGFpbGxlIjoiNTA5ODUiLCJkYXRlQ3JlYXRpb24iOiIyMDI1LTAzLTI3VDE4OjI4OjQ2LjcxMVoiLCJkYXRlTWFqIjoiMjAyNS0wMy0yN1QxODoyODo0Ni43MTFaIn19LCJpYXQiOjE3NDQzMTAyMTAsImV4cCI6MTc0NDMxMzgxMH0.LH-0H2hWkbZ601JsunOiVbV9fX5SdrwU4N-JYXoKs54

/*
GET http://localhost:3000/categories-articles/1
Content-Type: application/json
*/