POST https://testassbtapi.nataliesimon.fr/api/categories-activites/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3NDA5NDU0MDQsImV4cCI6MTc0MDk0OTAwNH0.PapPbHN9QSa_VCYPFFpDesgfZ2Gbd3sEKJE4n-x3h5g
{
  "lbl_categorie": "Accueil"
}
