POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "ybah2201@gmail.com"
}


POST http://localhost:3000/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoieWJhaDIyMDFAZ21haWwuY29tIiwiaWF0IjoxNzM5MTA1ODY3LCJleHAiOjE3MzkxMDk0Njd9.zJtuOzf92-f_jqLoikVezgZ4pCMMl7tdSxruf_ySwWs

{
  "nouveau_mdp": "abcdefghij"
}


