POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "ybah2201@gmail.com"
}


POST http://localhost:3000/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoieWJhaDIyMDFAZ21haWwuY29tIiwiaWF0IjoxNzM5MTA2NzA1LCJleHAiOjE3MzkxMTAzMDV9.YsXmgVLRG6pDMNo7f-oka5b9nJb9xA7YqzJaaY4aMw4

{
  "nouveau_mdp": "abcdefghij"
}


