GET http://localhost:3000/api/statuts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoieWJhaDIyMDFAZ21haWwuY29tIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5OTc2NTEwLCJleHAiOjE3Mzk5ODAxMTB9.elLdLISAoNkTR5Xv_KJoil-Xq5YLgGJUHBOqztKY6ac

/*GET http://localhost:3000/statuts/1
Content-Type: application/json*/