version: '3'

services:
  api:
    container_name: api_simple
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    networks:
      - web

networks:
  web:
    external: true