version: '3.8'

services:
  api:
    container_name: nestjs_api
    build:
      context: .
      dockerfile: ./Dockerfile.minimal
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api-prod.lesbulleurstoulonnais.fr`)"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.http.routers.api-http.rule=Host(`api-prod.lesbulleurstoulonnais.fr`)"
      - "traefik.http.routers.api-http.entrypoints=http"
      - "traefik.http.routers.api-http.middlewares=cors-open@file"

networks:
  app-network:
    driver: bridge
  web:
    external: true