FROM node:20-alpine

WORKDIR /app

RUN npm init -y && \
  npm install express

COPY <<-EOT /app/server.js
const express = require('express');
const app = express();

app.get('/', (req, res) => {
  res.send('API en ligne');
});

app.get('/accueil', (req, res) => {
  res.json({ message: 'Bienvenue sur l\'API' });
});

app.listen(3000, () => {
  console.log('Serveur démarré sur le port 3000');
});
EOT

EXPOSE 3000

CMD ["node", "server.js"]