name: Deploy NestJS with Prisma to OVH VPS (Dev)

on:
  workflow_dispatch:  # Permet uniquement le déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop  # Utilisation de la branche develop

      - name: Deploy to OVH VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY_OVH }}
          port: 2222  # Port SSH personnalisé
          script: |
            # Définition du répertoire racine sur le VPS
            VPS_ROOT="/home/deploy/app"
            APP_DIR="${VPS_ROOT}/nestjs-prisma"  # Répertoire pour la version Prisma

            # S'assurer que le répertoire d'application existe
            mkdir -p ${APP_DIR}

            # Vérifier l'état actuel
            echo "📂 Contenu actuel du répertoire de déploiement:"
            ls -la ${APP_DIR}

            # Nettoyage des conteneurs existants pour éviter les conflits
            echo "🧹 Nettoyage des conteneurs existants..."
            
            # Arrêter les conteneurs existants dans le répertoire nestjs
            if [ -d "${VPS_ROOT}/nestjs" ]; then
              cd "${VPS_ROOT}/nestjs"
              if [ -f "docker-compose.prod.yml" ]; then
                echo "📦 Arrêt des conteneurs dans ${VPS_ROOT}/nestjs"
                docker-compose -f docker-compose.prod.yml down || true
              fi
            fi
            
            # Arrêter les conteneurs existants dans le répertoire actuel
            if [ -f "${APP_DIR}/docker-compose.prisma.yml" ]; then
              cd ${APP_DIR}
              echo "📦 Arrêt des conteneurs dans ${APP_DIR}"
              docker-compose -f docker-compose.prisma.yml down || true
            fi
            
            # Suppression forcée de conteneurs spécifiques s'ils existent encore
            echo "🗑️ Suppression forcée des conteneurs potentiellement conflictuels..."
            docker rm -f postgres_db traefik api nestjs_api 2>/dev/null || true
            
            # Sauvegarde de la base de données si elle existe encore
            CONTAINER_RUNNING=$(docker ps -q -f name=postgres_db)
            if [ ! -z "$CONTAINER_RUNNING" ]; then
              echo "📦 Sauvegarde de la base de données avant suppression forcée..."
              mkdir -p ${APP_DIR}/backups
              CURRENT_DATE=$(date +"%Y%m%d_%H%M%S")
              
              # Déterminer les paramètres de connexion
              if [ -f "${APP_DIR}/.env.dev" ]; then
                source ${APP_DIR}/.env.dev
                DB_USER=${DB_USERNAME:-postgres}
                DB_NAME=${DB_NAME:-Assbt}
              else
                DB_USER="postgres"
                DB_NAME="Assbt"
              fi
              
              docker exec -t postgres_db pg_dump -U $DB_USER $DB_NAME > ${APP_DIR}/backups/db_${CURRENT_DATE}.sql || echo "⚠️ Échec de sauvegarde, poursuite du déploiement"
              
              # Suppression forcée après sauvegarde
              docker rm -f postgres_db
            fi

            # Préserver les fichiers importants
            cd ${APP_DIR}
            if [ -f "${APP_DIR}/.env.dev" ]; then
              echo "💾 Sauvegarde du fichier .env.dev actuel"
              cp ${APP_DIR}/.env.dev ${APP_DIR}/.env.dev.backup
            fi

            # Créer un répertoire temporaire pour le clone
            TMP_DIR=$(mktemp -d)
            echo "📋 Clonage du dépôt dans ${TMP_DIR}..."

            # Clone du dépôt GitHub
            git clone --depth=1 --branch=develop https://github.com/natalie-simon/assbt_api.git ${TMP_DIR}

            # Vérifier si le clone a réussi
            if [ $? -ne 0 ]; then
              echo "❌ Échec du clonage du dépôt"
              exit 1
            fi

            # Nettoyer le répertoire de l'application mais préserver .env.dev et backups
            echo "🧹 Nettoyage du répertoire de déploiement..."
            find ${APP_DIR} -mindepth 1 -not -path "${APP_DIR}/backups*" -not -name ".env.dev" -not -name ".env.dev.backup" -not -name "docker-compose.prisma.yml" -exec rm -rf {} \; 2>/dev/null || true

            # Copier les fichiers du dépôt cloné vers le répertoire de l'application
            echo "📋 Copie des fichiers du projet..."
            cp -R ${TMP_DIR}/* ${APP_DIR}/
            cp -R ${TMP_DIR}/.* ${APP_DIR}/ 2>/dev/null || true

            # Supprimer le répertoire temporaire
            rm -rf ${TMP_DIR}

            # Gestion du fichier .env.dev
            if [ ! -f "${APP_DIR}/.env.dev" ]; then
              echo "🔍 Fichier .env.dev non trouvé, recherche d'alternatives..."

              # Vérifier si .env.dev.backup existe
              if [ -f "${APP_DIR}/.env.dev.backup" ]; then
                echo "✅ Restauration du fichier .env.dev.backup"
                cp ${APP_DIR}/.env.dev.backup ${APP_DIR}/.env.dev
              # Vérifier si .env.dev existe dans le répertoire racine
              elif [ -f "${VPS_ROOT}/.env.dev" ]; then
                echo "✅ Copie du fichier .env.dev depuis ${VPS_ROOT}"
                cp ${VPS_ROOT}/.env.dev ${APP_DIR}/.env.dev
              else
                echo "⚠️ Aucun fichier .env.dev trouvé! Le déploiement pourrait échouer."
              fi
            fi

            # Vérifier le contenu après la copie
            echo "📂 Contenu du répertoire après copie:"
            ls -la ${APP_DIR}

            # Vérifier que docker-compose.prisma.yml existe
            if [ ! -f "${APP_DIR}/docker-compose.prisma.yml" ]; then
              echo "❌ Fichier docker-compose.prisma.yml non trouvé!"
              
              # Si le fichier n'existe pas mais que docker-compose.prod.yml existe, faire une copie
              if [ -f "${APP_DIR}/docker-compose.prod.yml" ]; then
                echo "✅ Utilisation de docker-compose.prod.yml en tant que docker-compose.prisma.yml"
                cp ${APP_DIR}/docker-compose.prod.yml ${APP_DIR}/docker-compose.prisma.yml
              else
                exit 1
              fi
            fi

            # Déployer l'application
            cd ${APP_DIR}
            echo "🚀 Déploiement de l'application..."
            docker-compose -f docker-compose.prisma.yml down || true
            
            # Démarrer d'abord la base de données seule
            echo "🔄 Démarrage de la base de données..."
            docker-compose -f docker-compose.prisma.yml up -d db
            
            # Attendre que la base de données soit prête
            echo "⏳ Attente que la base de données soit prête..."
            RETRIES=20
            RETRY_COUNT=0
            
            until docker-compose -f docker-compose.prisma.yml exec -T db pg_isready || [ $RETRY_COUNT -eq $RETRIES ]; do
              echo "🔄 En attente de la base de données... ($RETRY_COUNT/$RETRIES)"
              RETRY_COUNT=$((RETRY_COUNT+1))
              sleep 5
            done
            
            if [ $RETRY_COUNT -eq $RETRIES ]; then
              echo "⚠️ Base de données non disponible après $RETRIES tentatives. Poursuite du déploiement..."
            else
              echo "✅ Base de données prête"
            fi
            
            # Démarrer le reste des services
            echo "🚀 Démarrage des autres services..."
            docker-compose -f docker-compose.prisma.yml up -d --build
            
            # Attendre que l'API se lance
            echo "⏳ Attente du démarrage de l'API..."
            sleep 30

            # Vérifier l'état des services
            echo "📊 État des services après déploiement:"
            docker-compose -f docker-compose.prisma.yml ps

            # Gestion des migrations avec Prisma
            if docker-compose -f docker-compose.prisma.yml ps | grep -q "api"; then
              echo "🔄 Gestion des migrations Prisma..."
              
              # Étape 1: Générer le client Prisma
              echo "🔨 Génération du client Prisma..."
              docker-compose -f docker-compose.prisma.yml exec -T api npx prisma generate
              
              # Étape 2: Appliquer les migrations existantes
              echo "🔄 Application des migrations Prisma..."
              docker-compose -f docker-compose.prisma.yml exec -T api npx prisma migrate deploy
              
              # Si c'est la première exécution ou si le schéma a changé sans migration
              if [ $? -ne 0 ]; then
                echo "⚠️ Erreur lors de l'application des migrations. Vérification du schéma..."
                
                # Vérifier si des migrations existent déjà
                MIGRATIONS_EXIST=$(docker-compose -f docker-compose.prisma.yml exec -T api ls -la prisma/migrations 2>/dev/null | grep -v "total" | wc -l)
                
                if [ "$MIGRATIONS_EXIST" -eq "0" ]; then
                  echo "🔧 Aucune migration existante. Création de la première migration..."
                  docker-compose -f docker-compose.prisma.yml exec -T api npx prisma migrate dev --name init --create-only
                  docker-compose -f docker-compose.prisma.yml exec -T api npx prisma migrate deploy
                else
                  echo "🔍 Vérification de l'état de la base de données..."
                  docker-compose -f docker-compose.prisma.yml exec -T api npx prisma db pull
                  echo "📝 Création d'une migration de rattrapage..."
                  docker-compose -f docker-compose.prisma.yml exec -T api npx prisma migrate dev --name schema_sync --create-only
                  docker-compose -f docker-compose.prisma.yml exec -T api npx prisma migrate deploy
                fi
              fi
              
              # Vérification finale
              echo "🔍 Vérification de l'état des migrations Prisma..."
              docker-compose -f docker-compose.prisma.yml exec -T api npx prisma migrate status
            else
              echo "⚠️ Le service api n'est pas en cours d'exécution, migrations ignorées"
            fi
            
            # Vérifier les tables créées
            echo "📊 Vérification des tables de la base de données:"
            
            # Récupération des variables d'environnement depuis le fichier .env
            if [ -f "${APP_DIR}/.env.dev" ]; then
              source ${APP_DIR}/.env.dev
              DB_USER=${DB_USERNAME:-postgres}
              DB_NAME=${DB_NAME:-Assbt}
            else
              DB_USER="postgres"
              DB_NAME="Assbt"
            fi
            
            echo "📊 Vérification des tables dans $DB_NAME avec l'utilisateur $DB_USER"
            docker-compose -f docker-compose.prisma.yml exec -T db psql -U $DB_USER -d $DB_NAME -c "\dt" || echo "⚠️ Impossible de vérifier les tables"
            
            # Afficher les logs du service API
            echo "📃 Logs du service NestJS:"
            docker-compose -f docker-compose.prisma.yml logs --tail=50 api

            # Nettoyage
            echo "🧹 Nettoyage des images inutilisées..."
            docker image prune -f
