name: Deploy NestJS with Prisma to OVH VPS (Dev)

on:
  workflow_dispatch:  # Permet uniquement le déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev  # Force l'utilisation de la branche dev

      - name: Deploy to OVH VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY_OVH }}
          port: 2222  # Port SSH personnalisé
          script: |
            # Définition du répertoire racine sur le VPS
            VPS_ROOT="/home/deploy/app"
            APP_DIR="${VPS_ROOT}/nestjs-dev"  # Répertoire séparé pour l'environnement dev

            # S'assurer que le répertoire d'application existe
            mkdir -p ${APP_DIR}

            # Vérifier l'état actuel
            echo "📂 Contenu actuel du répertoire de déploiement:"
            ls -la ${APP_DIR}

            # Sauvegarde de la base de données si elle est en cours d'exécution
            if [ -f "${APP_DIR}/docker-compose.prod.yml" ]; then
              cd ${APP_DIR}
              if docker-compose -f docker-compose.prod.yml ps postgres_db 2>&1 | grep -q "Up"; then
                echo "📦 Sauvegarde de la base de données..."
                mkdir -p ${APP_DIR}/backups
                CURRENT_DATE=$(date +"%Y%m%d_%H%M%S")

                # Récupération des variables d'environnement depuis le fichier .env
                if [ -f "${APP_DIR}/.env.dev" ]; then
                  source ${APP_DIR}/.env.dev
                  DB_USER=${DB_USERNAME:-postgres}
                  DB_NAME=${DB_NAME:-Assbt}
                else
                  DB_USER="postgres"
                  DB_NAME="Assbt"
                fi

                echo "📊 Utilisation de la base de données: $DB_NAME avec l'utilisateur: $DB_USER"
                docker-compose -f docker-compose.prod.yml exec -T postgres_db pg_dump -U $DB_USER $DB_NAME > ${APP_DIR}/backups/db_${CURRENT_DATE}.sql || echo "⚠️ Échec de sauvegarde, poursuite du déploiement"
              fi
            fi

            # Préserver les fichiers importants
            cd ${APP_DIR}
            if [ -f "${APP_DIR}/.env.dev" ]; then
              echo "💾 Sauvegarde du fichier .env.dev actuel"
              cp ${APP_DIR}/.env.dev ${APP_DIR}/.env.dev.backup
            fi

            # Copier les fichiers du dépôt
            echo "📋 Copie des fichiers du projet..."

            # Vider le répertoire tout en préservant les fichiers critiques
            find ${APP_DIR} -mindepth 1 -not -path "${APP_DIR}/backups*" -not -name ".env.dev" -not -name ".env.dev.backup" -not -name "docker-compose.prod.yml" -exec rm -rf {} \; 2>/dev/null || true

            # Copier tous les fichiers locaux vers le VPS
            scp -r $(pwd)/* deploy@${{ secrets.VPS_HOST }}:${APP_DIR}/

            # Gestion du fichier .env.dev
            if [ ! -f "${APP_DIR}/.env.dev" ]; then
              echo "🔍 Fichier .env.dev non trouvé, recherche d'alternatives..."

              # Vérifier si .env.dev.backup existe
              if [ -f "${APP_DIR}/.env.dev.backup" ]; then
                echo "✅ Restauration du fichier .env.dev.backup"
                cp ${APP_DIR}/.env.dev.backup ${APP_DIR}/.env.dev
              # Vérifier si .env.dev existe dans le répertoire racine
              elif [ -f "${VPS_ROOT}/.env.dev" ]; then
                echo "✅ Copie du fichier .env.dev depuis ${VPS_ROOT}"
                cp ${VPS_ROOT}/.env.dev ${APP_DIR}/.env.dev
              else
                echo "⚠️ Aucun fichier .env.dev trouvé! Le déploiement pourrait échouer."
              fi
            fi

            # Vérifier que docker-compose.prod.yml existe
            if [ ! -f "${APP_DIR}/docker-compose.prod.yml" ]; then
              echo "❌ Fichier docker-compose.prod.yml non trouvé!"
              # Utiliser le fichier docker-compose.prisma.yml s'il existe
              if [ -f "${APP_DIR}/docker-compose.prisma.yml" ]; then
                echo "✅ Utilisation de docker-compose.prisma.yml à la place"
                cp ${APP_DIR}/docker-compose.prisma.yml ${APP_DIR}/docker-compose.prod.yml
              else
                exit 1
              fi
            fi

            # Déployer l'application
            cd ${APP_DIR}
            echo "🚀 Déploiement de l'application..."
            docker-compose -f docker-compose.prod.yml down || true

            # Démarrer d'abord la base de données seule
            echo "🔄 Démarrage de la base de données..."
            docker-compose -f docker-compose.prod.yml up -d db

            # Attendre que la base de données soit prête
            echo "⏳ Attente que la base de données soit prête..."
            RETRIES=20
            RETRY_COUNT=0

            until docker-compose -f docker-compose.prod.yml exec -T db pg_isready || [ $RETRY_COUNT -eq $RETRIES ]; do
              echo "🔄 En attente de la base de données... ($RETRY_COUNT/$RETRIES)"
              RETRY_COUNT=$((RETRY_COUNT+1))
              sleep 5
            done

            if [ $RETRY_COUNT -eq $RETRIES ]; then
              echo "⚠️ Base de données non disponible après $RETRIES tentatives. Poursuite du déploiement..."
            else
              echo "✅ Base de données prête"
            fi

            # Démarrer le reste des services
            echo "🚀 Démarrage des autres services..."
            docker-compose -f docker-compose.prod.yml up -d --build

            # Attendre que l'API se lance
            echo "⏳ Attente du démarrage de l'API..."
            sleep 30

            # Vérifier l'état des services
            echo "📊 État des services après déploiement:"
            docker-compose -f docker-compose.prod.yml ps

            # Gestion des migrations avec Prisma
            if docker-compose -f docker-compose.prod.yml ps | grep -q "api"; then
              echo "🔄 Gestion des migrations Prisma..."

              # Étape 1: Générer le client Prisma
              echo "🔨 Génération du client Prisma..."
              docker-compose -f docker-compose.prod.yml exec -T api npx prisma generate

              # Étape 2: Appliquer les migrations existantes
              echo "🔄 Application des migrations Prisma..."
              docker-compose -f docker-compose.prod.yml exec -T api npx prisma migrate deploy

              # Vérification finale
              echo "🔍 Vérification de l'état des migrations Prisma..."
              docker-compose -f docker-compose.prod.yml exec -T api npx prisma migrate status
            else
              echo "⚠️ Le service api n'est pas en cours d'exécution, migrations ignorées"
            fi

            # Vérifier les tables créées
            echo "📊 Vérification des tables de la base de données:"

            # Récupération des variables d'environnement depuis le fichier .env
            if [ -f "${APP_DIR}/.env.dev" ]; then
              source ${APP_DIR}/.env.dev
              DB_USER=${DB_USERNAME:-postgres}
              DB_NAME=${DB_NAME:-Assbt}
            else
              DB_USER="postgres"
              DB_NAME="Assbt"
            fi

            echo "📊 Vérification des tables dans $DB_NAME avec l'utilisateur $DB_USER"
            docker-compose -f docker-compose.prod.yml exec -T db psql -U $DB_USER -d $DB_NAME -c "\dt" || echo "⚠️ Impossible de vérifier les tables"

            # Afficher les logs du service API
            echo "📃 Logs du service NestJS:"
            docker-compose -f docker-compose.prod.yml logs --tail=50 api

            # Nettoyage
            echo "🧹 Nettoyage des images inutilisées..."
            docker image prune -f