name: Deploy Traefik to OVH VPS

on:
  push:
    branches:
    - develop

jobs:
  deploy-traefik:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Traefik directories
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY_OVH }}
          port: 2222
          script: |
            echo "Creating Traefik directories..."
            mkdir -p ~/app/traefik/config
            mkdir -p ~/app/traefik/dynamic
            mkdir -p ~/app/traefik/acme
            touch ~/app/traefik/acme/acme.json
            chmod 600 ~/app/traefik/acme/acme.json

            echo "Creating traefik.yml..."
            cat > ~/app/traefik/config/traefik.yml << 'EOL'
            api:
              dashboard: true
              debug: true

            entryPoints:
              http:
                address: ":80"
                http:
                  redirections:
                    entryPoint:
                      to: https
                      scheme: https
              https:
                address: ":443"

            providers:
              docker:
                endpoint: "unix:///var/run/docker.sock"
                exposedByDefault: false
                network: web
              file:
                directory: "/etc/traefik/dynamic"
                watch: true

            certificatesResolvers:
              letsencrypt:
                acme:
                  email: votre@email.com
                  storage: "/etc/traefik/acme/acme.json"
                  httpChallenge:
                    entryPoint: http
            EOL

            echo "Creating dynamic_conf.yml..."
            cat > ~/app/traefik/dynamic/dynamic_conf.yml << 'EOL'
            http:
              middlewares:
                secureHeaders:
                  headers:
                    sslRedirect: true
                    forceSTSHeader: true
                    stsIncludeSubdomains: true
                    stsPreload: true
                    stsSeconds: 31536000
            EOL
            echo "Configuration files created successfully"