name: Deploy Traefik to OVH VPS

on:
  workflow_dispatch:

jobs:
  deploy-traefik:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Traefik directories
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY_OVH }}
          port: 2222
          script: |
            echo "Creating Traefik directories..."
            mkdir -p ~/app/traefik/config
            mkdir -p ~/app/traefik/dynamic
            mkdir -p ~/app/traefik/acme
            touch ~/app/traefik/acme/acme.json
            chmod 600 ~/app/traefik/acme/acme.json
            echo "Directories created successfully"
            ls -la ~/app/traefik/